export const QUIZ_UNIT_CONSTANTS = {
  START_QUIZ: 0,
  RESUME_QUIZ: 2,
  VIEW_RESULT: 1,
};

export const TIME_ENABLE_CONSTANTS = {
  ENABLE_SECTION_TIME: '0',
  ENABLE_QUESTION_TIME: '1',
  ENABLE_QUIZ_TIME: '2',
};
