export const data = {
  userName: 'Abhishek',
  studentDashboardList: [
    {
      id: 1,
      cardTitle: 'Minutes',
      cardIcon: '',
      value: 410,
      cardDetail: 'Total Watch Time',
      isCardActive: true,
    },
    {
      id: 2,
      cardTitle: 'Ques.',
      cardIcon: '',
      value: 3000,
      cardDetail: 'Ques. Attempted',
      isCardActive: true,
    },
    {
      id: 3,
      cardTitle: 'Lessons',
      cardIcon: '',
      value: 126,
      cardDetail: 'Lessons Completed',
      isCardActive: true,
    },
    {
      id: 4,
      cardTitle: 'Full Test',
      cardIcon: '',
      value: 126,
      cardDetail: 'Full Test Attempted',
      isCardActive: false,
    },
    {
      id: 5,
      cardTitle: 'Doubts',
      cardIcon: '',
      value: 410,
      cardDetail: 'Doubts Asked',
      isCardActive: true,
    },
    {
      id: 6,
      cardTitle: 'Goals',
      cardIcon: '',
      value: 4,
      cardDetail: 'Goals Achieved',
      isCardActive: true,
    },
  ],
  leaderBoardList: [
    {
      name: 'Rajesh J',
      score: '2323',
      rank: '1',
      image: 'url image',
      isTopper: true,
      isSelf: false,
      correct_answers: 2323,
      type: 'gold/silver/bronze/other',
    },
    {
      name: 'Rajesh J',
      score: '2323',
      rank: '1',
      image: 'url image',
      isTopper: true,
      isSelf: false,
      correct_answers: 2323,
      type: 'gold/silver/bronze/other',
    },
  ],
};
